### ISSUE TITLE
snli_match_lstm_predict.py

### ISSUE THREAD

**Issue by cxf712** [junfenglx/reasoning_attention#1]
where did you use word2vector?Out-of-vocabulary words on the test corpus are set to fixed random vectors in the paper.but, in the"snli_match_lstm_predict.py",you use "print('Warning: {} not in dictionary'.format(w))" to handle the oov.why?

**Comment by junfenglx** [comment]
Hello @cxf712 
The file `snli_match_lstm_predict.py` is just for prediction using trained match-lstm model,
you provide two sentences, it will give you a relationship between them.
The OOV words printed are words not in SNLI corpus.

When train match-lstm, we use Word2vec pre-trained model, and tune OOV words,
see README notes.
